### ISSUE TITLE
Export X509.Certificate.self_signed?/1 function

### ISSUE THREAD

**Issue by tanguilp** [voltone/x509#18]
Hi,

Just a suggestion: as I'm trying to implement https://tools.ietf.org/html/draft-ietf-oauth-mtls-12#section-2.2 wouldn't it be nice to expose such a function? Which is basically just :public_key.pkix_is_self_signed/1

**Comment by voltone** [comment]
I would like to avoid this library becoming a thin wrapper around `:public_key`: the goal is to provide high-level functions for more complex operations, such as issuing certificates, or functionality not provided by OTP, such as deriving a public key from a private key.

All relevant return types are Erlang records that can be used as-is with `:public_key`.

Thanks for the suggestion, and do let me know if you have any other needs/issues!
