### ISSUE TITLE
Dialyzer and opaque types

### ISSUE THREAD

**Issue by fhunleth** [voltone/x509#20]
I'm currently fighting Dialyzer warnings since I periodically need to reach into various types. For example, part of a program I'm working on manages X.509 certificates in a compressed format. I have code that pulls out fields from the `X509.Certificate` (like the signature and validity) and then puts them into an analogous, but smaller data structure.This causes a problem with Dialyzer since many types in `x509` are declared `opaque`. 

Making the types non-opaque is a fix, but I'm not sure if that's the direction you wanted for this library. 

This is probably a rare use case, but if you'd like to see some partially complete code, it's here: https://github.com/fhunleth/atecc508a/blob/real_hw/lib/atecc508a/certificate.ex#L60. To pass Dialyzer, I currently need to remove the opaque on `X509.Certificate.t()`, `X509.Certificate.Extension.t()`, and `X509.Certificate.Validity()`.

**Comment by voltone** [comment]
As you may have noticed, I have not yet gotten round to running Dialyzer on the package. The typespecs are there primarily for documentation purposes. If there are typespecs that need fixing, by all means, let's do it.

For the types you mention I definitely agree they should not be opaque: I specifically intended to use types defined in `:public_key` as much as possible, and I wanted the typespecs to reflect that.

Are these the only Dialyzer issues you've encountered? Surely there must be more...?

**Comment by fhunleth** [comment]
No worries. I just posted #21 to fix the issues that affect me. There are a few other Dialyzer warnings so I posted #22 if you were interested in looking.

**Comment by voltone** [comment]
Thanks a lot! I will merge #21 for now, and will play with Dialyzer when I have some more time.
