### ISSUE TITLE
Unknown type public_key:ec_public_key/0

### ISSUE THREAD

**Issue by martinos** [voltone/x509#27]
I am new to elixir and I try to use a typespec for one of my function.

```
  @spec fetch_key(String.t()) :: {:ok, X509.PublicKey.t()} | {:error, any()}
  def fetch_key(url) do
    CertValidation.fetch_valid_pub_key(url)
  end
```

When I run dialyzer I get the following error message:

```
:0: Unknown type public_key:ec_public_key/0
:0: Unknown type public_key:rsa_public_key/0
```
Do you have an idea of what might be the issue?

**Comment by voltone** [comment]
Yes, this is a known issue (see #22). As I mentioned there, `:public_key` does not expose the types used in the docs, and I wanted to use those types in my docs to stress the compatibility the native types used in `:public_key` and `:ssl`.

This may get resolved as part of the extraction of core functionality to an Erlang package.
