### ISSUE TITLE
[Question] CSR with extension subject_alt_name

### ISSUE THREAD

**Issue by kaitsh** [voltone/x509#31]
Thanks for this great lib!

I'd like to request a cert from let's encrypt and I need to provide a CSR with the domain names as subject alt name. The subject common names are ignored (see issue https://github.com/letsencrypt/pebble/issues/233)

How can I generate a CSR with SAN?

**Comment by voltone** [comment]
Thanks for the feedback. Would you be able to give #32 a spin and let me know if Let's Encrypt is happy with the output? I may want to clean up the code a bit before merging, but it would be great to first verify that it works.

**Comment by kaitsh** [comment]
Wow, that was fast. Just tested and it works perfectly. Keep up the great work! 💪

**Comment by voltone** [comment]
Merged and published as 0.8.0, but note that the API changed slightly: the `:extensions` option now takes a simple list of extension values, rather than a keyword list.
