### ISSUE TITLE
Use Erlang {:ok, result} style for more convenient matching

### ISSUE THREAD

**Issue by fhunleth** [voltone/x509#8]
Unfortunately this is a backwards incompatible API change, but since `x509` is pre-1.0, I figured that I'd try proposing it. The problem that I'm running into is that several functions return a result or `nil` if they fail. For example, the pem/der conversion functions do this (e.g. https://github.com/voltone/x509/blob/master/lib/x509/private_key.ex#L168.) 

Here's what happens in my code. This is what I'll want to do:

```elixir
with {:ok, contents} <- FIle.read("cert.pem"),
  {:ok, cert} <- X509.Certificate.from_pem do
  # do something with the cert
end
```

Since I can't do that, I could write:

```elixir
with {:ok, contents} <- FIle.read("cert.pem"),
  cert when not is_nil(cert) <- X509.Certificate.from_pem(contents) do
  # do something with the cert
else
  nil -> {:error, :pem_decode_failed}
end
```
But that's not as concise. Since you have the corresponding bang! versions of the functions, it seems natural to do the Erlang `{:ok, result}` thing with the non-bang! ones.

If this breaks too much code or you prefer the current style, feel free to ignore. Your library is helping me out quite a bit as it is.

**Comment by voltone** [comment]
This API change is already work in progress, see the changelog for 0.3.0 for details. The CSR module pretty much implements the new API I'm aiming for in the next release. Please have a look and let me know if that would work for you.

**Comment by voltone** [comment]
See also https://github.com/sasa1977/site_encrypt/pull/14 for why the change is being done across two minor versions: I didn't want to break Saša's code
