### ISSUE TITLE
Support for revoking a certificate

### ISSUE THREAD

**Issue by fhunleth** [voltone/x509#9]
Do you have plans for creating an API for creating a CRL or adding a new certificate to a CRL?

**Comment by voltone** [comment]
Yes, and I also want to add helpers for building OCSP clients/servers (see https://blog.voltone.net/post/21).

I'll keep this one open to track the progress on CRL support. Thanks!

**Comment by fhunleth** [comment]
Nice! This library is great, btw. We're actively refactoring calls out to `openssl` and `cfssl` in NervesHub with calls here, and it's really simplifying our code.

**Comment by voltone** [comment]
Cool, that's exactly what I intended this library for: I kept seeing people use OpenSSL for things that OTP can do out of the box.

Please keep the feedback coming: I don't have an immediate need for this package myself, so I don't know what works well and what doesn't. And seeing people use it will push me to work on it some more...
